/*
 * This source file was generated by the Gradle 'init' task
 */
package club.netheril.convert_3gpp_excel;

import java.io.FileInputStream;

import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length != 1) {
            throw new IllegalArgumentException(
                    String.format("We expect only one command argument, i.e., path to the excel file. But we got '%s'",
                            String.join(", ", args)));
        }
        try {
            FileInputStream file = new FileInputStream(args[0]);
            XSSFWorkbook wb = new XSSFWorkbook(file);
            XSSFSheet sheet = wb.getSheetAt(0);
            System.out.println("== cell ==");
            System.out.println(SheetParserUtils.safeGetCellString(sheet, ExcelCellIndex.of(3, 3)));
            System.out.println("== /cell ==");
            wb.close();

        } catch (Throwable e) {
            throw new IllegalArgumentException(
                    String.format("Failed to parse Excel file '%s' as a 3GPP spec table.", args[0]),
                    e);
        }

        System.out.println(new App().getGreeting());
    }
}
