/*
 * This source file was generated by the Gradle 'init' task
 */
package club.netheril.convert_3gpp_excel;

import java.io.FileInputStream;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class App {

  public static void run(String excelFileName) {
    try {
      FileInputStream file = new FileInputStream(excelFileName);
      XSSFWorkbook wb = new XSSFWorkbook(file);
      TableMetadata metadata = MetadataSheetParser.parse(wb);
      TableData data = TableSheetParser.parse(wb, metadata);
      System.out.println(
          String.format("Successfully parsed Excel file %s, data =\n%s\n", excelFileName, data));
      wb.close();

    } catch (Throwable e) {
      throw new IllegalArgumentException(
          String.format("Failed to parse Excel file '%s' as a 3GPP spec table", excelFileName), e);
    }
  }

  public static void main(String[] args) {
    if (args.length != 1) {
      throw new IllegalArgumentException(
          String.format(
              "We expect only one command argument, i.e., path to the excel file. But we got '%s'",
              String.join(", ", args)));
    }
    run(args[0]);
  }
}
