/*
 * This source file was generated by the Gradle 'init' task
 */
package club.netheril.convert_3gpp_excel;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    App converter = new App();
  }
}
