/*
 * This source file was generated by the Gradle 'init' task
 */
package club.netheril.convert_3gpp_excel;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
  @Test
  public void parseExcelFileSucceed() {
    String excelFileUrl =
        getClass().getClassLoader().getResource("table_5.5A.3.2-1.xlsx").toString();
    assertTrue(excelFileUrl.startsWith("file:"));

    TableData tableData = App.parseExcelFile(excelFileUrl.substring("file:".length()));
    assertTrue(tableData.rows().size() > 0);
  }
}
